In [1]:
import pandas as pd
import numpy as np

In [2]:
dfYelp = pd.read_csv('../../yelp-dataset/checkin_money_merge.csv', 
                     dtype={'Unamed: 0': int,
                           'business_id' : object,
                           'stars' : float,
                           'review_count' : float,
                           'is_open' : float,
                           'categories' : object,
                           'Median' : float,
                           'Mean' : object,
                           'Pop' : float,
                           'checkins' : float})
dfYelp = dfYelp.fillna(0);

In [3]:
'''
I decided to drop Mean income category becasue it is not a good 
indicator of the general populaiton and can be 
skewed by very rich or very poor outliers.
'''
dfYelp.drop('Unnamed: 0', axis = 1, inplace=True)
dfYelp.drop('Mean', axis = 1, inplace=True)
dfYelp.drop(dfYelp[dfYelp.Median == 0].index, inplace=True)

In [4]:
"""Grouping by business id, and taking the average of the dataframe only truly returns the average of the number of checkins
becasue the checkins were join to business id in a previous file. Each checkin instance for a unique business_id has redundant data
for all other attributes 
"""
dfYelp = dfYelp.groupby(['business_id', 'categories'], as_index=False)['stars','review_count', 'is_open','Median','Pop','checkins'].mean()

In [5]:
#https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/
dfYelp.groupby(['stars'])['business_id'].count()

stars
0.0        1
1.0     2849
1.5     3174
2.0     6877
2.5    11638
3.0    15778
3.5    21855
4.0    23096
4.5    18347
5.0    23764
Name: business_id, dtype: int64

In [6]:
#https://stackoverflow.com/questions/33271098/python-get-a-frequency-count-based-on-two-columns-variables-in-pandas-datafra
dfYelp.groupby(["stars", "is_open"]).size().reset_index(name="NumberOfStars_IsOpen")

    stars  is_open  NumberOfStars_IsOpen
0     0.0      0.0                     1
1     1.0      0.0                   338
2     1.0      1.0                  2511
3     1.5      0.0                   456
4     1.5      1.0                  2718
5     2.0      0.0                   989
6     2.0      1.0                  5888
7     2.5      0.0                  1992
8     2.5      1.0                  9646
9     3.0      0.0                  3244
10    3.0      1.0                 12534
11    3.5      0.0                  4159
12    3.5      1.0                 17696
13    4.0      0.0                  3937
14    4.0      1.0                 19159
15    4.5      0.0                  2490
16    4.5      1.0                 15857
17    5.0      0.0                  2147
18    5.0      1.0                 21617

In [7]:
#Median 223106
#pop 113916
#checkin 1478
#review count 7361

custom_bin_median = np.linspace(0,225000,20)
custom_bin_pop = np.linspace(0,115000,20)
custom_bin_checkins = np.linspace(0,1500,20)
custom_bin_review_count = np.linspace(0,7500,20)

dfYelp['Median'] = pd.cut(dfYelp['Median'], custom_bin_median)
dfYelp['Pop'] = pd.cut(dfYelp['Pop'], custom_bin_pop)
dfYelp['checkins'] = pd.cut(dfYelp['checkins'], custom_bin_checkins)

In [8]:
dfYelp_groupby = dfYelp.groupby(['business_id', 'categories'], as_index=False)['stars','review_count', 'is_open','Median','Pop','checkins'].mean();

In [9]:
dfYelp_groupby.head(10)

,business_id,categories,stars,review_count,is_open
0,0,0,0.0,0.0,0.0
1,--7zmmkVg-IMGaXbuVd0SQ,Food;Breweries,4.0,47.0,1.0
2,--8LPVSo5i0Oo61X01sV9A,Orthopedists;Weight Loss Centers;Sports Medici...,4.5,3.0,1.0
3,--9QQLMTbFzLJ_oT-ON3Xw,Hair Salons;Beauty & Spas,3.5,11.0,1.0
4,--9e1ONYQuAa-CB_Rrw7Tw,Cajun/Creole;Steakhouses;Restaurants,4.0,1451.0,1.0
5,--DdmeR16TRb3LsjG0ejrQ,Arts & Entertainment;Festivals,3.0,5.0,1.0
6,--EF5N7P70J_UYBTPypYlA,Beauty & Spas;Nail Salons,3.0,3.0,1.0
7,--EX4rRznJrltyn-34Jz1w,Shopping;Cosmetics & Beauty Supply;Beauty & Spas,4.0,4.0,1.0
8,--FBCX-N37CMYDfs790Bnw,Food;American (New);Nightlife;Bars;Beer;Wine &...,3.5,108.0,1.0
9,--FLdgM0GNpXVMn74ppCGw,Physical Therapy;Health & Medical,3.5,6.0,1.0

In [10]:
dfYelp.head(10)

,business_id,categories,stars,review_count,is_open,Median,Pop,checkins
0,0,0,0.0,0.0,0.0,"(47368.421, 59210.526]","(6052.632, 12105.263]",NaN
1,--7zmmkVg-IMGaXbuVd0SQ,Food;Breweries,4.0,47.0,1.0,"(82894.737, 94736.842]","(24210.526, 30263.158]","(0.0, 78.947]"
2,--8LPVSo5i0Oo61X01sV9A,Orthopedists;Weight Loss Centers;Sports Medici...,4.5,3.0,1.0,"(71052.632, 82894.737]","(48421.053, 54473.684]","(0.0, 78.947]"
3,--9QQLMTbFzLJ_oT-ON3Xw,Hair Salons;Beauty & Spas,3.5,11.0,1.0,"(47368.421, 59210.526]","(42368.421, 48421.053]","(0.0, 78.947]"
4,--9e1ONYQuAa-CB_Rrw7Tw,Cajun/Creole;Steakhouses;Restaurants,4.0,1451.0,1.0,"(35526.316, 47368.421]","(6052.632, 12105.263]","(0.0, 78.947]"
5,--DdmeR16TRb3LsjG0ejrQ,Arts & Entertainment;Festivals,3.0,5.0,1.0,"(35526.316, 47368.421]","(6052.632, 12105.263]","(0.0, 78.947]"
6,--EF5N7P70J_UYBTPypYlA,Beauty & Spas;Nail Salons,3.0,3.0,1.0,"(59210.526, 71052.632]","(30263.158, 36315.789]",NaN
7,--EX4rRznJrltyn-34Jz1w,Shopping;Cosmetics & Beauty Supply;Beauty & Spas,4.0,4.0,1.0,"(35526.316, 47368.421]","(24210.526, 30263.158]","(0.0, 78.947]"
8,--FBCX-N37CMYDfs790Bnw,Food;American (New);Nightlife;Bars;Beer;Wine &...,3.5,108.0,1.0,"(71052.632, 82894.737]","(12105.263, 18157.895]","(0.0, 78.947]"
9,--FLdgM0GNpXVMn74ppCGw,Physical Therapy;Health & Medical,3.5,6.0,1.0,"(82894.737, 94736.842]","(36315.789, 42368.421]","(0.0, 78.947]"

In [11]:
#dfYelp.to_csv('test.csv')

In [12]:
dfYelp['Median'].describe()

count                     127379
unique                        12
top       (47368.421, 59210.526]
freq                       30631
Name: Median, dtype: object

In [13]:
dfYelp['Pop'].describe()

count                     127379
unique                        13
top       (36315.789, 42368.421]
freq                       21974
Name: Pop, dtype: object

In [14]:
dfYelp['checkins'].describe()

count            106440
unique                6
top       (0.0, 78.947]
freq             106393
Name: checkins, dtype: object

In [15]:
print(custom_bin_pop)

[      0.            6052.63157895   12105.26315789   18157.89473684
   24210.52631579   30263.15789474   36315.78947368   42368.42105263
   48421.05263158   54473.68421053   60526.31578947   66578.94736842
   72631.57894737   78684.21052632   84736.84210526   90789.47368421
   96842.10526316  102894.73684211  108947.36842105  115000.        ]